  - id: 1
    alias: Turn on Fishtank Light
    trigger:
    - platform: state
      entity_id: sun.sun
      from: below_horizon
      to: above_horizon
    action:
    - service: switch.turn_on
      entity_id: switch.fishtanklights

  - id: 2
    alias: Turn on Fishtank Light
    trigger:
    - platform: state
      entity_id: sun.sun
      from: above_horizon
      to: below_horizon
    action:
    - service: switch.turn_off
      entity_id: switch.fishtanklights