- id: '1'
  alias: Turn on Fish Light
  trigger:
  - entity_id: sun.sun
    from: below_horizon
    platform: state
    to: above_horizon
  action:
  - entity_id: switch.fishtanklights
    service: switch.turn_on
  mode: single
- id: '2'
  alias: Turn off Fish Light
  trigger:
  - entity_id: sun.sun
    from: above_horizon
    platform: state
    to: below_horizon
  action:
  - entity_id: switch.fishtanklights
    service: switch.turn_off
  mode: single
- id: '3'
  alias: Feed Fish
  trigger:
  - at: '09:00'
    platform: time
  - at: '17:00'
    platform: time
  action:
  - entity_id: switch.fishfeeder
    service: switch.turn_on
  - entity_id: switch.fishfilter
    service: switch.turn_off
  - delay: 00:00:02
  - entity_id: switch.fishfeeder
    service: switch.turn_off
  - delay: 00:05:00
  - entity_id: switch.fishfilter
    service: switch.turn_on
  mode: single
- id: '4'
  alias: Turn on Front Door Lights
  trigger:
  - entity_id: binary_sensor.door_sensor
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - entity_id: switch.entrydoorlight
    service: switch.turn_on
  - entity_id: switch.entrywhitelight
    service: switch.turn_on
  mode: single
- id: '5'
  alias: Turn off Front Door Lights
  trigger:
  - entity_id: binary_sensor.door_sensor
    platform: state
    to: 'off'
  action:
  - delay: 00:00:45
  - entity_id: switch.entrydoorlight
    service: switch.turn_off
  - entity_id: switch.entrywhitelight
    service: switch.turn_off
  mode: single
