homeassistant:
  name: Home
  elevation: 0
  latitude: 22.908194
  longitude: 44.421476
  unit_system: metric
  time_zone: Europe/Berlin

frontend:
config:
http:
  server_port: 80

discovery:
conversation:
history:
logbook:
map:
sun:
system_health:

mqtt:
  broker: localhost
  username: sub_client
  password: 10293847
