---
# tasks file for ha
- name: Install Packages
  ansible.builtin.dnf:
    name:
      - python3-devel
      - redhat-rpm-config
    state: latest

- name: Add the user 'homeassistant' with a bash shell, appending the group dialout
  ansible.builtin.user:
    name: homeassistant
    shell: /bin/bash
    groups: dialout,wheel
    append: yes

- name: Setup password less sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Delete HA working directory
  ansible.builtin.file:
    path: /opt/homeassistant
    state: absent
  ignore_errors: yes

- name: Make HA working directory
  ansible.builtin.file:
    path: /opt/homeassistant
    state: directory
    mode: '0755'
    owner: homeassistant
    group: homeassistant

- name: Setup venv for Python3
  become: yes
  become_user: homeassistant
  become_method: sudo
  become_flags: '-H -s'
  shell: /usr/bin/python -m venv /opt/homeassistant/

- name: Setup venv for Python3
  become: yes
  become_user: homeassistant
  become_method: sudo
  become_flags: '-H -s'
  shell: . /opt/homeassistant/bin/activate && pip3 install homeassistant colorlog
  args:
     executable: /bin/bash

- name: Allow home assistant port
  firewalld:
    port: 8123/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Template a file for systemd
  template:
    src: home-assistant.j2
    dest: /etc/systemd/system/home-assistant@homeassistant.service

- name: Just force systemd to re-execute itself (2.8 and above)
  ansible.builtin.systemd:
    daemon_reexec: yes

- name: Enable ha service
  ansible.builtin.systemd:
    name: home-assistant@homeassistant.service
    state: started
    enabled: yes
