---
# tasks file for ha
- name: Install Packages
  ansible.builtin.dnf:
    name:
      - python3-devel
      - redhat-rpm-config
    state: latest

- name: Add the user 'homeassistant' with a bash shell, appending the group dialout
  ansible.builtin.user:
    name: homeassistant
    shell: /bin/bash
    groups: dialout,wheel
    append: yes

- name: Setup password less sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Make HA working directory
  ansible.builtin.file:
    path: /opt/homeassistant
    state: directory
    mode: '0755'
    owner: homeassistant
    group: homeassistant

- name: Setup venv for Python3
  become: yes
  become_user: homeassistant
  become_method: sudo
  ansible.builtin.command: 'python -m venv . && source bin/activate && pip3 install homeassistant colorlog'
  args:
    chdir: /opt/homeassistant

- name: Allow home assistant port
  ansible.posix.firewalld:
    port: 8123/tcp
    permanent: yes
    state: enabled
    immediate: yes
