---
# tasks file for haConfig
- include_vars: "vault"
- name: Template for configs
  template:
    src: "{{ item }}.j2"
    dest: "/opt/homeassistant/.homeassistant/{{ item }}"
  with_items:
    - configuration.yaml
    - automations.yaml
    - binary_sensor.yaml
    - customize.yaml
    - groups.yaml
    - scenes.yaml
    - scripts.yaml
    - sensor.yaml
    - switch.yaml

- name: Install Packages
  ansible.builtin.dnf:
    name:
      - mosquitto
    state: latest

- name: Create file for mosquitto passwd
  ansible.builtin.file:
    path: /etc/mosquitto/passwd
    state: touch
    owner: root
    group: root
    mode: '0644'

- name: Setup password for MQTT
  lineinfile:
    path: /etc/mosquitto/passwd
    state: present
    regexp: '^client:'
    line: 'client:$6$l2s4N6jfovuCfMey$yHPLGpGrfleUzEy8m0NPmNcUXbrnVxOImS1Lze0xaiXLx8qx0WFxFUwUjjOLCcSD4QN2Ca46sPUkVeFK26jQAw=='
  
- name: Enable ha service
  ansible.builtin.systemd:
    name: mosquitto.service
    state: started
    enabled: yes