---
# tasks file for haConfig
- include_vars: "vault"
- name: Template for configuration.yaml
  template:
    src: configuration.yaml.j2
    dest: /opt/homeassistant/.homeassistant/configuration.yaml

- name: Install Packages
  ansible.builtin.dnf:
    name:
      - mosquitto
    state: latest

- name: Run command to set MQTT password for client
  ansible.builtin.command: /usr/bin/mosquitto_passwd -c /etc/mosquitto/passwd client "{{ mqtt_pass }}"

- name: Enable ha service
  ansible.builtin.systemd:
    name: mosquitto.service
    state: started
    enabled: yes