---
# tasks file for haConfig
- include_vars: "vault"
- name: Template for configuration.yaml
  template:
    src: configuration.yaml.j2
    dest: /opt/homeassistant/.homeassistant/configuration.yaml

- name: Install Packages
  ansible.builtin.dnf:
    name:
      - mosquitto
    state: latest

- name: Create file for mosquitto passwd
  ansible.builtin.file:
    path: /etc/mosquitto/passwd
    state: present
    owner: root
    group: root
    mode: '0644'

- name: Setup password for MQTT
  lineinfile:
    path: /etc/mosquitto/passwd
    state: present
    regexp: '^client:'
    line: 'client:$6$l2s4N6jfovuCfMey$yHPLGpGrfleUzEy8m0NPmNcUXbrnVxOImS1Lze0xaiXLx8qx0WFxFUwUjjOLCcSD4QN2Ca46sPUkVeFK26jQAw=='
    validate: 'visudo -cf %s'
  
- name: Enable ha service
  ansible.builtin.systemd:
    name: mosquitto.service
    state: started
    enabled: yes